version: '3'

services:
    db:
        image: postgres
        container_name: postgres-coleta-seletiva
        restart: always
        volumes:
            - pgdata:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: 1234
        ports:
            - 5432:5432
volumes:
    pgdata: